server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.xml

jwt:
  secret: YmFua2NhcmRzLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHk=
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
